default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ganga19.
  host: localhost

development:
  <<: *default
  database: irrigation_development

test:
  <<: *default
  database: irrigation_test

production:
  <<: *default
  database: irrigation_production
